<?php
const ALL_VERIFICATION_ARRAY = [
    "empty_input" => "Заполните все поля",
    "invalid_uid" => "Неверный формат пользователя",
    "invalid_email" => "Неверный формат почты",
    "incorrect_format_password" => "Неверный формат пароля",
    "user_not_found" => "Пользователь не найден",
    "incorrect_user_or_password" => "Неверно введен логин или пароль",
    "password_doesnt_match" => "Пароли не совпадают",
    "user_or_mail_taken" => "Пользователь уже существует",
    "user_deleted" => "Аккаунт удален",
    "session_not_found" => "Авторизируйтесь в системе",
    "access_denied" => "Нет прав доступа, авторизируйтесь в системе",
];
const ALL_TABLE_ARRAY = [
    "in_system" => "Вы уже в системе",
    "access_denied" => "Недостаточно прав доступа",
    "empty_input" => "Заполните все поля",
    "invalid_uid" => "Неверный формат пользователя",
    "incorrect_format_password" => "Неверный формат пароля в форме",
    "password_doesnt_match" => "Пароли в форме не совпадают",
    "user_or_mail_taken" => "Пользователь уже существует",
    "user_deleted" => "Аккаунт удален",
    "session_not_found" => "Авторизируйтесь в системе",
    "success_create" => "Пользователь добавлен в систему",
    "success_register" => "Вы успешно зарегестрировались",
    "success_delete" => "Пользователь удален",
    "success_edit" => "Пользователь изменен",
    "success_recover" => "Пользователь восстановлен",
    "old_input" => "Введите новые данные",
    "access_myself_denied" => "Пользователь в системе может внести изменения только в профиле",
    "file_exist" => "Sorry, file already exists.",
    "file_large" => "Sorry, your file is too large.",
    "file_incorrect" => "Некорректный формат фотографии",
    "fatal_error" => "Sorry, your file was not uploaded.",
    "delete_myself" => "Разве это выход?",
    "invalid_title_course" => "Некорректное название",
    "invalid_description_course" => "Некорректное описание",

];
